const admin = [
  {
    firstName: "",
    lastName: "",
    commission: 0,
    agent_level: "O",
    user_name: "galaxy",
    email: "",
    newPassword: false,
    password: "Abcd1234",
    email_verified_at: null,
    limit: 0,
    admin: null,
    whoAdd: [],
    domain: ["648a9f2a61bb8552f1df16d7"],
    agent: [],
    player: [],
    mobileNumber: "",
    status: "active",
    balance: 0,
    remaining_balance: 0,
    exposure: 0,
    cumulative_pl: 0,
    ref_pl: 0,
    credit_ref: 0,
    exposer_limit: 0,
    rolling_delay: false,
    commissionAmount: 0.0,
  },
];
module.exports = admin;
