const defaultSportLimit = {
  cricket: {
    oddsLimit: {
      min: 552,
      max: 1,
      maxProfit: 11,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_odds_limit: {
      min: 50,
      max: 50,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_bookmaker_limit: {
      min: 5,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_fancy_limit: {
      min: 10,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_premium_limit: {
      min: 2,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
  },
  setAutoSportsAdd: {
    cricket: true,
    soccer: false,
    tennis: false,
  },
  setAutoSportsResult: {
    cricket: true,
    soccer: false,
    tennis: false,
  },
  soccer: {
    oddsLimit: {
      min: 0,
      max: 10,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_odds_limit: {
      min: 0,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_bookmaker_limit: {
      min: 0,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_premium_limit: {
      min: 0,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
  },
  tennis: {
    oddsLimit: {
      min: 0,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_odds_limit: {
      min: 0,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_bookmaker_limit: {
      min: 0,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
    bet_premium_limit: {
      min: 0,
      max: 0,
      maxProfit: 0,
      betDelay: 0,
      maxPrice: 0,
      isShow: false,
    },
  },
};

module.exports = defaultSportLimit;
